services:
  - type: web
    name: cfms-backend
    runtime: node
    repo: https://github.com/Wanderajonah/cfms
    branch: main
    rootDir: backend
    buildCommand: npm install
    startCommand: node server.js
    envVars:
      - key: NODE_VERSION
        value: 18
      - key: MONGO_URI
        sync: false
      - key: JWT_SECRET
        sync: false
      - key: GROQ_API_KEY
        sync: false
